FROM nginx:latest

# support running as arbitrary user which belogs to the root group
RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx /etc/nginx

WORKDIR '/'

RUN mkdir -p /run/nginx /www/data

# Provided in this Docker package, and relatively simple configs
COPY ./cac/default.template.conf /etc/nginx/conf.d/default.template.conf

#this script pulls the dns server out of /etc/resolv.conf so we can
#use it as the nginx resolver
COPY ./shared/get_dns.sh /get_dns.sh
COPY ./shared/nginx_entrypoint.sh /nginx_entrypoint.sh
RUN chmod +x /get_dns.sh /nginx_entrypoint.sh

COPY ./cac/jquery.min.js /www/data/jquery.min.js

# self-signed server cert
COPY ./cac/certificate.pem /etc/nginx

# self-signed server privkey
COPY ./cac/key.pem         /etc/nginx

# https://github.com/mpyne-navy/nginx-cac/blob/master/Makefile
COPY ./cac/DoDRoots.crt    /etc/nginx

ENTRYPOINT [ "sh", "-c", "/nginx_entrypoint.sh" ]