version: '3'
services:
    client:
        image: quay.agilesof.com/soceur/node:alpine
        build:
            context: ./
            dockerfile: ./client/Dockerfile
        ports:
            - '3000:3000'
    api:
        image: quay.agilesof.com/soceur/node:alpine
        build:
            context: ./
            dockerfile: ./api/Dockerfile
        depends_on:
            - mongodb
        environment:
            WAIT_HOSTS: mongodb:27017
        links:
            - mongodb
    mongodb:
        image: quay.agilesof.com/soceur/mongo:latest
        ports:
            - 27017:27017
        command: mongod --noauth
        volumes:
            - mongodata:/data/db
    nginx:
        image: quay.agilesof.com/soceur/nginx:latest
        restart: always
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        ports:
            - '8000:8443'
    cac:
        image: quay.agilesof.com/soceur/nginx:latest
        restart: always
        build:
            context: ./
            dockerfile: ./cac/Dockerfile
        ports:
            - '7000:8443'
