#tell compose to get build its images from the git repo
#format is budget.git#branch:folder

version: '3'
services:
    client:
        build:
            context: https://github.com/mcleanra/budget.git#docker-prod
            dockerfile: ./client/Dockerfile
        volumes:
            - /packages/client/node_modules
            - ./client:/packages/client
            - ./shared:/packages/shared
        environment:
            - CHOKIDAR_USEPOLLING=true
    api:
        build:
            context: https://github.com/mcleanra/budget.git#docker-prod
            dockerfile: ./api/Dockerfile
        volumes:
            - /packages/api/node_modules
            - ./api:/packages/api
            - ./shared:/packages/shared
        depends_on:
            - mongodb
        environment:
            WAIT_HOSTS: mongodb:27017
        links:
            - mongodb
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        command: mongod --noauth
    nginx:
        restart: always
        build:
            context: https://github.com/mcleanra/budget.git#docker-prod
            dockerfile: ./nginx/Dockerfile
        ports:
            - '8000:443'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    cac:
        restart: always
        build:
            context: https://github.com/mcleanra/budget.git#docker-prod
            dockerfile: ./cac/Dockerfile
        ports:
            - '7000:443'
        volumes:
            - ./cac/default.conf:/etc/nginx/conf.d/default.conf
            - ./cac/index.html:/www/data/index.html
