#tell compose to get build its images from the git repo
#format is budget.git#branch:folder

version: '3'
services:
    client:
        image: quay.agilesof.com/soceur/node:alpine
        build: ./client
        volumes:
            - /packages/client/node_modules
            - ./client:/packages/client
            - ./shared:/packages/shared
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - '3000:3000'
    api:
        image: quay.agilesof.com/soceur/node:alpine
        build: ./api
        volumes:
            - /packages/api/node_modules
            - ./api:/packages/api
            - ./shared:/packages/shared
        depends_on:
            - mongodb
        environment:
            WAIT_HOSTS: mongodb:27017
        links:
            - mongodb
        ports:
            - '9000:9000'
    mongodb:
        image: quay.agilesof.com/soceur/mongo:latest
        ports:
            - 27017:27017
        command: mongod --noauth
    nginx:
        restart: always
        image: quay.agilesof.com/soceur/nginx:latest
        build: ./nginx
        ports:
            - '8000:8443'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    cac:
        restart: always
        image: quay.agilesof.com/soceur/nginx:latest
        build: ./cac
        ports:
            - '7000:8443'
        volumes:
            - ./cac/default.conf:/etc/nginx/conf.d/default.conf
            - ./cac/index.html:/www/data/index.html
