version: '3'
services:
    client:
        image: redoubt.azurecr.us/node:alpine
        build:
            context: ./
            dockerfile: ./client/Dockerfile
        ports:
            - '3000:3000'
    api:
        image: redoubt.azurecr.us/node:alpine
        build:
            context: ./
            dockerfile: ./api/Dockerfile
        depends_on:
            - mongodb
        environment:
            WAIT_HOSTS: mongodb:27017
        links:
            - mongodb
    mongodb:
        image: redoubt.azurecr.us/mongo:latest
        ports:
            - 27017:27017
        command: mongod --noauth
    nginx:
        image: redoubt.azurecr.us/nginx:latest
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '8000:443'
    cac:
        image: redoubt.azurecr.us/nginx:latest
        restart: always
        build:
            context: ./cac
            dockerfile: Dockerfile
        ports:
            - '7000:443'
