apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.agilesof.com/soceur/node:alpine
    generation: null
    importPolicy: {}
    name: alpine
status:
  dockerImageRepository: ""
