apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\prod-from-git-with-images2.yml --provider openshift --build build-config
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: cac
  name: cac
spec:
  ports:
  - name: "7000"
    port: 7000
    targetPort: 443
  selector:
    io.kompose.service: cac
status:
  loadBalancer: {}
