apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\prod-from-git-with-images2.yml --provider openshift --build build-config
      --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: cac
  name: cac
spec:
  replicas: 1
  selector:
    io.kompose.service: cac
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cac
    spec:
      containers:
      - image: ' '
        name: cac
        ports:
        - containerPort: 443
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - cac
      from:
        kind: ImageStreamTag
        name: cac:latest
    type: ImageChange
status: {}
