apiVersion: v1
kind: DeploymentConfig
metadata:
    annotations:
        kompose.cmd:
            C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
            convert -f .\prod-from-git-with-images2.yml --provider openshift --build build-config
            --volumes hostPath
        kompose.version: 1.20.0 (f3d54d784)
    creationTimestamp: null
    labels:
        io.kompose.service: client
    name: client
spec:
    replicas: 1
    selector:
        io.kompose.service: client
    strategy:
        resources: {}
    template:
        metadata:
            creationTimestamp: null
            labels:
                io.kompose.service: client
        spec:
            containers:
                - env:
                      - name: CHOKIDAR_USEPOLLING
                        value: 'true'
                  image: ' '
                  name: client
                  resources: {}
            restartPolicy: Always
    test: false
    triggers:
        - type: ConfigChange
        - imageChangeParams:
              automatic: true
              containerNames:
                  - client
              from:
                  kind: ImageStreamTag
                  name: client:alpine
          type: ImageChange
status: {}
