apiVersion: v1
kind: BuildConfig
metadata:
    annotations:
        kompose.cmd:
            C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
            convert -f .\prod-from-git-with-images2.yml --provider openshift --build build-config
            --volumes hostPath
        kompose.version: 1.20.0 (f3d54d784)
    creationTimestamp: null
    labels:
        io.kompose.service: mongodb
    name: mongodb
spec:
    nodeSelector: null
    output:
        to:
            kind: ImageStreamTag
            name: mongodb:3.6.15-xenial
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
        contextDir: /
        git:
            ref: docker-prod
            uri: https://github.com/mcleanra/budget.git
        type: Git
    strategy:
        dockerStrategy:
            dockerfilePath: mongodb/Dockerfile
        type: Docker
    triggers:
        - type: ConfigChange
status:
    lastVersion: 0
