apiVersion: v1
kind: DeploymentConfig
metadata:
    annotations:
        kompose.cmd:
            C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
            convert -f .\prod-from-git-with-images2.yml --provider openshift --build build-config
            --volumes hostPath
        kompose.version: 1.20.0 (f3d54d784)
    creationTimestamp: null
    labels:
        io.kompose.service: mongodb
    name: mongodb
spec:
    replicas: 1
    selector:
        io.kompose.service: mongodb
    strategy:
        resources: {}
    template:
        metadata:
            creationTimestamp: null
            labels:
                io.kompose.service: mongodb
        spec:
            containers:
                image: ' '
                name: mongodb
                ports:
                    - containerPort: 27017
                resources: {}
            restartPolicy: Always
    test: false
    triggers:
        - type: ConfigChange
        - imageChangeParams:
              automatic: true
              containerNames:
                  - mongodb
              from:
                  kind: ImageStreamTag
                  name: mongodb:3.6.15-xenial
          type: ImageChange
status: {}
