apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\prod-from-git-with-images2.yml --provider openshift --build build-config
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nginx:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: nginx/
    git:
      ref: docker-prod
      uri: https://github.com/mcleanra/budget.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
