FROM nginx:latest

RUN mkdir -p /run/nginx /www/data

# Provided in this Docker package, and relatively simple configs
COPY ./nginx/default.conf /etc/nginx/conf.d/default.template

#this script pulls the dns server out of /etc/resolv.conf so we can
#use it as the nginx resolver
COPY ./shared/get_dns.sh /get_dns.sh
COPY ./shared/nginx_entrypoint.sh /nginx_entrypoint.sh
RUN chmod +x /get_dns.sh /nginx_entrypoint.sh

# self-signed server cert
COPY ./nginx/certificate.pem /etc/nginx

# self-signed server privkey
COPY ./nginx/key.pem         /etc/nginx

# https://github.com/mpyne-navy/nginx-cac/blob/master/Makefile
COPY ./nginx/DoDRoots.crt    /etc/nginx

ENTRYPOINT [ "sh", "-c", "/nginx_entrypoint.sh" ]

CMD ["/usr/sbin/nginx", "-q", "-g", "daemon off;"]